<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'افغانستان', 'name_en' => 'Afghanistan', 'code' => 'AFG', 'flag' => '🇦🇫', 'sort_order' => 1],
            ['name' => 'آلبانی', 'name_en' => 'Albania', 'code' => 'ALB', 'flag' => '🇦🇱', 'sort_order' => 2],
            ['name' => 'الجزایر', 'name_en' => 'Algeria', 'code' => 'DZA', 'flag' => '🇩🇿', 'sort_order' => 3],
            ['name' => 'ساموآی آمریکا', 'name_en' => 'American Samoa', 'code' => 'ASM', 'flag' => '🇦🇸', 'sort_order' => 4],
            ['name' => 'آندورا', 'name_en' => 'Andorra', 'code' => 'AND', 'flag' => '🇦🇩', 'sort_order' => 5],
            ['name' => 'آنگولا', 'name_en' => 'Angola', 'code' => 'AGO', 'flag' => '🇦🇴', 'sort_order' => 6],
            ['name' => 'آنگویلا', 'name_en' => 'Anguilla', 'code' => 'AIA', 'flag' => '🇦🇮', 'sort_order' => 7],
            ['name' => 'جنوبگان', 'name_en' => 'Antarctica', 'code' => 'ANA', 'flag' => '', 'sort_order' => 8],
            ['name' => 'آنتیگوا و باربودا', 'name_en' => 'Antigua and Barbuda', 'code' => 'ATG', 'flag' => '🇦🇬', 'sort_order' => 9],
            ['name' => 'آرژانتین', 'name_en' => 'Argentina', 'code' => 'ARG', 'flag' => '🇦🇷', 'sort_order' => 10],
            ['name' => 'ارمنستان', 'name_en' => 'Armenia', 'code' => 'ARM', 'flag' => '🇦🇲', 'sort_order' => 11],
            ['name' => 'آروبا', 'name_en' => 'Aruba', 'code' => 'ABW', 'flag' => '🇦🇼', 'sort_order' => 12],
            ['name' => 'استرالیا', 'name_en' => 'Australia', 'code' => 'AUS', 'flag' => '🇦🇺', 'sort_order' => 13],
            ['name' => 'اتریش', 'name_en' => 'Austria', 'code' => 'AUT', 'flag' => '🇦🇹', 'sort_order' => 14],
            ['name' => 'جمهوری آذربایجان', 'name_en' => 'Azerbaijan', 'code' => 'AZE', 'flag' => '🇦🇿', 'sort_order' => 15],
            ['name' => 'باهاما', 'name_en' => 'Bahamas', 'code' => 'BHS', 'flag' => '🇧🇸', 'sort_order' => 16],
            ['name' => 'بحرین', 'name_en' => 'Bahrain', 'code' => 'BHR', 'flag' => '🇧🇭', 'sort_order' => 17],
            ['name' => 'بنگلادش', 'name_en' => 'Bangladesh', 'code' => 'BGD', 'flag' => '🇧🇩', 'sort_order' => 18],
            ['name' => 'باربادوس', 'name_en' => 'Barbados', 'code' => 'BRB', 'flag' => '🇧🇧', 'sort_order' => 19],
            ['name' => 'بلاروس', 'name_en' => 'Belarus', 'code' => 'BLR', 'flag' => '🇧🇾', 'sort_order' => 20],
            ['name' => 'بلژیک', 'name_en' => 'Belgium', 'code' => 'BEL', 'flag' => '🇧🇪', 'sort_order' => 21],
            ['name' => 'بلیز', 'name_en' => 'Belize', 'code' => 'BLZ', 'flag' => '🇧🇿', 'sort_order' => 22],
            ['name' => 'بنین', 'name_en' => 'Benin', 'code' => 'BEN', 'flag' => '🇧🇯', 'sort_order' => 23],
            ['name' => 'برمودا', 'name_en' => 'Bermuda', 'code' => 'BMU', 'flag' => '🇧🇲', 'sort_order' => 24],
            ['name' => 'بوتان', 'name_en' => 'Bhutan', 'code' => 'BTN', 'flag' => '🇧🇹', 'sort_order' => 25],
            ['name' => 'بولیوی', 'name_en' => 'Bolivia', 'code' => 'BOL', 'flag' => '🇧🇴', 'sort_order' => 26],
            ['name' => 'بوسنی و هرزگوین', 'name_en' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'flag' => '🇧🇦', 'sort_order' => 27],
            ['name' => 'بوتسوانا', 'name_en' => 'Botswana', 'code' => 'BWA', 'flag' => '🇧🇼', 'sort_order' => 28],
            ['name' => 'جزیره بووه', 'name_en' => 'Bouvet Island', 'code' => 'BV', 'flag' => '', 'sort_order' => 29],
            ['name' => 'برزیل', 'name_en' => 'Brazil', 'code' => 'BRA', 'flag' => '🇧🇷', 'sort_order' => 30],
            ['name' => 'قلمرو اقیانوس هند بریتانیا', 'name_en' => 'British Indian Ocean Territory', 'code' => 'IOT', 'flag' => '', 'sort_order' => 31],
            ['name' => 'برونئی', 'name_en' => 'Brunei Darussalam', 'code' => 'BRN', 'flag' => '🇧🇳', 'sort_order' => 32],
            ['name' => 'بلغارستان', 'name_en' => 'Bulgaria', 'code' => 'BGR', 'flag' => '🇧🇬', 'sort_order' => 33],
            ['name' => 'بورکینافاسو', 'name_en' => 'Burkina Faso', 'code' => 'BFA', 'flag' => '🇧🇫', 'sort_order' => 34],
            ['name' => 'بوروندی', 'name_en' => 'Burundi', 'code' => 'BDI', 'flag' => '🇧🇮', 'sort_order' => 35],
            ['name' => 'کامبوج', 'name_en' => 'Cambodia', 'code' => 'KHM', 'flag' => '🇰🇭', 'sort_order' => 36],
            ['name' => 'کامرون', 'name_en' => 'Cameroon', 'code' => 'CMR', 'flag' => '🇨🇲', 'sort_order' => 37],
            ['name' => 'کانادا', 'name_en' => 'Canada', 'code' => 'CAN', 'flag' => '🇨🇦', 'sort_order' => 38],
            ['name' => 'کیپ ورد', 'name_en' => 'Cape Verde', 'code' => 'CPV', 'flag' => '🇨🇻', 'sort_order' => 39],
            ['name' => 'جزایر کیمن', 'name_en' => 'Cayman Islands', 'code' => 'CYM', 'flag' => '🇰🇾', 'sort_order' => 40],
            ['name' => 'جمهوری آفریقای مرکزی', 'name_en' => 'Central African Republic', 'code' => 'CAF', 'flag' => '🇨🇫', 'sort_order' => 41],
            ['name' => 'چاد', 'name_en' => 'Chad', 'code' => 'TCD', 'flag' => '🇹🇩', 'sort_order' => 42],
            ['name' => 'شیلی', 'name_en' => 'Chile', 'code' => 'CHL', 'flag' => '🇨🇱', 'sort_order' => 43],
            ['name' => 'چین', 'name_en' => 'China', 'code' => 'CHN', 'flag' => '🇨🇳', 'sort_order' => 44],
            ['name' => 'جزیره کریسمس', 'name_en' => 'Christmas Island', 'code' => 'CX', 'flag' => '', 'sort_order' => 45],
            ['name' => 'جزایر کوکوس', 'name_en' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'flag' => '', 'sort_order' => 46],
            ['name' => 'کلمبیا', 'name_en' => 'Colombia', 'code' => 'COL', 'flag' => '🇨🇴', 'sort_order' => 47],
            ['name' => 'کومور', 'name_en' => 'Comoros', 'code' => 'COM', 'flag' => '🇰🇲', 'sort_order' => 48],
            ['name' => 'کنگو', 'name_en' => 'Congo', 'code' => 'COG', 'flag' => '🇨🇬', 'sort_order' => 49],
            ['name' => 'جمهوری دموکراتیک کنگو', 'name_en' => 'Congo, the Democratic Republic of the', 'code' => 'COD', 'flag' => '🇨🇩', 'sort_order' => 50],
            ['name' => 'جزایر کوک', 'name_en' => 'Cook Islands', 'code' => 'COK', 'flag' => '🇨🇰', 'sort_order' => 51],
            ['name' => 'کاستاریکا', 'name_en' => 'Costa Rica', 'code' => 'CRI', 'flag' => '🇨🇷', 'sort_order' => 52],
            ['name' => 'ساحل عاج', 'name_en' => 'Cote D\'Ivoire', 'code' => 'CIV', 'flag' => '🇨🇮', 'sort_order' => 53],
            ['name' => 'کرواسی', 'name_en' => 'Croatia', 'code' => 'HRV', 'flag' => '🇭🇷', 'sort_order' => 54],
            ['name' => 'کوبا', 'name_en' => 'Cuba', 'code' => 'CUB', 'flag' => '🇨🇺', 'sort_order' => 55],
            ['name' => 'قبرس', 'name_en' => 'Cyprus', 'code' => 'CYP', 'flag' => '🇨🇾', 'sort_order' => 56],
            ['name' => 'جمهوری چک', 'name_en' => 'Czech Republic', 'code' => 'CZE', 'flag' => '🇨🇿', 'sort_order' => 57],
            ['name' => 'دانمارک', 'name_en' => 'Denmark', 'code' => 'DNK', 'flag' => '🇩🇰', 'sort_order' => 58],
            ['name' => 'جیبوتی', 'name_en' => 'Djibouti', 'code' => 'DJI', 'flag' => '🇩🇯', 'sort_order' => 59],
            ['name' => 'دومینیکا', 'name_en' => 'Dominica', 'code' => 'DMA', 'flag' => '🇩🇲', 'sort_order' => 60],
            ['name' => 'جمهوری دومینیکن', 'name_en' => 'Dominican Republic', 'code' => 'DOM', 'flag' => '🇩🇴', 'sort_order' => 61],
            ['name' => 'اکوادور', 'name_en' => 'Ecuador', 'code' => 'ECU', 'flag' => '🇪🇨', 'sort_order' => 62],
            ['name' => 'مصر', 'name_en' => 'Egypt', 'code' => 'EGY', 'flag' => '🇪🇬', 'sort_order' => 63],
            ['name' => 'السالوادور', 'name_en' => 'El Salvador', 'code' => 'SLV', 'flag' => '🇸🇻', 'sort_order' => 64],
            ['name' => 'گینه استوایی', 'name_en' => 'Equatorial Guinea', 'code' => 'GNQ', 'flag' => '🇬🇶', 'sort_order' => 65],
            ['name' => 'اریتره', 'name_en' => 'Eritrea', 'code' => 'ERI', 'flag' => '🇪🇷', 'sort_order' => 66],
            ['name' => 'استونی', 'name_en' => 'Estonia', 'code' => 'EST', 'flag' => '🇪🇪', 'sort_order' => 67],
            ['name' => 'اتیوپی', 'name_en' => 'Ethiopia', 'code' => 'ETH', 'flag' => '🇪🇹', 'sort_order' => 68],
            ['name' => 'جزایر فالکلند', 'name_en' => 'Falkland Islands (Malvinas)', 'code' => 'FLK', 'flag' => '🇫🇰', 'sort_order' => 69],
            ['name' => 'جزایر فارو', 'name_en' => 'Faroe Islands', 'code' => 'FRO', 'flag' => '🇫🇴', 'sort_order' => 70],
            ['name' => 'فیجی', 'name_en' => 'Fiji', 'code' => 'FJI', 'flag' => '🇫🇯', 'sort_order' => 71],
            ['name' => 'فنلاند', 'name_en' => 'Finland', 'code' => 'FIN', 'flag' => '🇫🇮', 'sort_order' => 72],
            ['name' => 'فرانسه', 'name_en' => 'France', 'code' => 'FRA', 'flag' => '🇫🇷', 'sort_order' => 73],
            ['name' => 'گویان فرانسه', 'name_en' => 'French Guiana', 'code' => 'GUF', 'flag' => '🇬🇫', 'sort_order' => 74],
            ['name' => 'پلینزی فرانسه', 'name_en' => 'French Polynesia', 'code' => 'PYF', 'flag' => '🇵🇫', 'sort_order' => 75],
            ['name' => 'سرزمین‌های جنوبی فرانسه', 'name_en' => 'French Southern Territories', 'code' => 'TF', 'flag' => '', 'sort_order' => 76],
            ['name' => 'گابن', 'name_en' => 'Gabon', 'code' => 'GAB', 'flag' => '🇬🇦', 'sort_order' => 77],
            ['name' => 'گامبیا', 'name_en' => 'Gambia', 'code' => 'GMB', 'flag' => '🇬🇲', 'sort_order' => 78],
            ['name' => 'گرجستان', 'name_en' => 'Georgia', 'code' => 'GEO', 'flag' => '🇬🇪', 'sort_order' => 79],
            ['name' => 'آلمان', 'name_en' => 'Germany', 'code' => 'DEU', 'flag' => '🇩🇪', 'sort_order' => 80],
            ['name' => 'غنا', 'name_en' => 'Ghana', 'code' => 'GHA', 'flag' => '🇬🇭', 'sort_order' => 81],
            ['name' => 'جبل‌الطارق', 'name_en' => 'Gibraltar', 'code' => 'GIB', 'flag' => '🇬🇮', 'sort_order' => 82],
            ['name' => 'یونان', 'name_en' => 'Greece', 'code' => 'GRC', 'flag' => '🇬🇷', 'sort_order' => 83],
            ['name' => 'گرینلند', 'name_en' => 'Greenland', 'code' => 'GRL', 'flag' => '🇬🇱', 'sort_order' => 84],
            ['name' => 'گرنادا', 'name_en' => 'Grenada', 'code' => 'GRD', 'flag' => '🇬🇩', 'sort_order' => 85],
            ['name' => 'گوادلوپ', 'name_en' => 'Guadeloupe', 'code' => 'GLP', 'flag' => '🇬🇵', 'sort_order' => 86],
            ['name' => 'گوام', 'name_en' => 'Guam', 'code' => 'GUM', 'flag' => '🇬🇺', 'sort_order' => 87],
            ['name' => 'گواتمالا', 'name_en' => 'Guatemala', 'code' => 'GTM', 'flag' => '🇬🇹', 'sort_order' => 88],
            ['name' => 'گینه', 'name_en' => 'Guinea', 'code' => 'GIN', 'flag' => '🇬🇳', 'sort_order' => 89],
            ['name' => 'گینه بیسائو', 'name_en' => 'Guinea-Bissau', 'code' => 'GNB', 'flag' => '🇬🇼', 'sort_order' => 90],
            ['name' => 'گویان', 'name_en' => 'Guyana', 'code' => 'GUY', 'flag' => '🇬🇾', 'sort_order' => 91],
            ['name' => 'هائیتی', 'name_en' => 'Haiti', 'code' => 'HTI', 'flag' => '🇭🇹', 'sort_order' => 92],
            ['name' => 'جزیره هرد و جزایر مک‌دونالد', 'name_en' => 'Heard Island and Mcdonald Islands', 'code' => 'HM', 'flag' => '', 'sort_order' => 93],
            ['name' => 'واتیکان', 'name_en' => 'Holy See (Vatican City State)', 'code' => 'VAT', 'flag' => '🇻🇦', 'sort_order' => 94],
            ['name' => 'هندوراس', 'name_en' => 'Honduras', 'code' => 'HND', 'flag' => '🇭🇳', 'sort_order' => 95],
            ['name' => 'هنگ کنگ', 'name_en' => 'Hong Kong', 'code' => 'HKG', 'flag' => '🇭🇰', 'sort_order' => 96],
            ['name' => 'مجارستان', 'name_en' => 'Hungary', 'code' => 'HUN', 'flag' => '🇭🇺', 'sort_order' => 97],
            ['name' => 'ایسلند', 'name_en' => 'Iceland', 'code' => 'ISL', 'flag' => '🇮🇸', 'sort_order' => 98],
            ['name' => 'هند', 'name_en' => 'India', 'code' => 'IND', 'flag' => '🇮🇳', 'sort_order' => 99],
            ['name' => 'اندونزی', 'name_en' => 'Indonesia', 'code' => 'IDN', 'flag' => '🇮🇩', 'sort_order' => 100],
            ['name' => 'ایران', 'name_en' => 'Iran, Islamic Republic of', 'code' => 'IRN', 'flag' => '🇮🇷', 'sort_order' => 101],
            ['name' => 'عراق', 'name_en' => 'Iraq', 'code' => 'IRQ', 'flag' => '🇮🇶', 'sort_order' => 102],
            ['name' => 'ایرلند', 'name_en' => 'Ireland', 'code' => 'IRL', 'flag' => '🇮🇪', 'sort_order' => 103],
            ['name' => 'اسرائیل', 'name_en' => 'Israel', 'code' => 'ISR', 'flag' => '🇮🇱', 'sort_order' => 104],
            ['name' => 'ایتالیا', 'name_en' => 'Italy', 'code' => 'ITA', 'flag' => '🇮🇹', 'sort_order' => 105],
            ['name' => 'جامائیکا', 'name_en' => 'Jamaica', 'code' => 'JAM', 'flag' => '🇯🇲', 'sort_order' => 106],
            ['name' => 'ژاپن', 'name_en' => 'Japan', 'code' => 'JPN', 'flag' => '🇯🇵', 'sort_order' => 107],
            ['name' => 'اردن', 'name_en' => 'Jordan', 'code' => 'JOR', 'flag' => '🇯🇴', 'sort_order' => 108],
            ['name' => 'قزاقستان', 'name_en' => 'Kazakhstan', 'code' => 'KAZ', 'flag' => '🇰🇿', 'sort_order' => 109],
            ['name' => 'کنیا', 'name_en' => 'Kenya', 'code' => 'KEN', 'flag' => '🇰🇪', 'sort_order' => 110],
            ['name' => 'کیریباتی', 'name_en' => 'Kiribati', 'code' => 'KIR', 'flag' => '🇰🇮', 'sort_order' => 111],
            ['name' => 'کره شمالی', 'name_en' => 'Korea, Democratic People\'s Republic of', 'code' => 'PRK', 'flag' => '🇰🇵', 'sort_order' => 112],
            ['name' => 'کره جنوبی', 'name_en' => 'Korea, Republic of', 'code' => 'KOR', 'flag' => '🇰🇷', 'sort_order' => 113],
            ['name' => 'کویت', 'name_en' => 'Kuwait', 'code' => 'KWT', 'flag' => '🇰🇼', 'sort_order' => 114],
            ['name' => 'قرقیزستان', 'name_en' => 'Kyrgyzstan', 'code' => 'KGZ', 'flag' => '🇰🇬', 'sort_order' => 115],
            ['name' => 'لائوس', 'name_en' => 'Lao People\'s Democratic Republic', 'code' => 'LAO', 'flag' => '🇱🇦', 'sort_order' => 116],
            ['name' => 'لتونی', 'name_en' => 'Latvia', 'code' => 'LVA', 'flag' => '🇱🇻', 'sort_order' => 117],
            ['name' => 'لبنان', 'name_en' => 'Lebanon', 'code' => 'LBN', 'flag' => '🇱🇧', 'sort_order' => 118],
            ['name' => 'لسوتو', 'name_en' => 'Lesotho', 'code' => 'LSO', 'flag' => '🇱🇸', 'sort_order' => 119],
            ['name' => 'لیبریا', 'name_en' => 'Liberia', 'code' => 'LBR', 'flag' => '🇱🇷', 'sort_order' => 120],
            ['name' => 'لیبی', 'name_en' => 'Libyan Arab Jamahiriya', 'code' => 'LBY', 'flag' => '🇱🇾', 'sort_order' => 121],
            ['name' => 'لیختن‌اشتاین', 'name_en' => 'Liechtenstein', 'code' => 'LIE', 'flag' => '🇱🇮', 'sort_order' => 122],
            ['name' => 'لیتوانی', 'name_en' => 'Lithuania', 'code' => 'LTU', 'flag' => '🇱🇹', 'sort_order' => 123],
            ['name' => 'لوکزامبورگ', 'name_en' => 'Luxembourg', 'code' => 'LUX', 'flag' => '🇱🇺', 'sort_order' => 124],
            ['name' => 'ماکائو', 'name_en' => 'Macao', 'code' => 'MAC', 'flag' => '🇲🇴', 'sort_order' => 125],
            ['name' => 'مقدونیه', 'name_en' => 'Macedonia, the Former Yugoslav Republic of', 'code' => 'MKD', 'flag' => '🇲🇰', 'sort_order' => 126],
            ['name' => 'ماداگاسکار', 'name_en' => 'Madagascar', 'code' => 'MDG', 'flag' => '🇲🇬', 'sort_order' => 127],
            ['name' => 'مالاوی', 'name_en' => 'Malawi', 'code' => 'MWI', 'flag' => '🇲🇼', 'sort_order' => 128],
            ['name' => 'مالزی', 'name_en' => 'Malaysia', 'code' => 'MYS', 'flag' => '🇲🇾', 'sort_order' => 129],
            ['name' => 'مالدیو', 'name_en' => 'Maldives', 'code' => 'MDV', 'flag' => '🇲🇻', 'sort_order' => 130],
            ['name' => 'مالی', 'name_en' => 'Mali', 'code' => 'MLI', 'flag' => '🇲🇱', 'sort_order' => 131],
            ['name' => 'مالتا', 'name_en' => 'Malta', 'code' => 'MLT', 'flag' => '🇲🇹', 'sort_order' => 132],
            ['name' => 'جزایر مارشال', 'name_en' => 'Marshall Islands', 'code' => 'MHL', 'flag' => '🇲🇭', 'sort_order' => 133],
            ['name' => 'مارتینیک', 'name_en' => 'Martinique', 'code' => 'MTQ', 'flag' => '🇲🇶', 'sort_order' => 134],
            ['name' => 'موریتانی', 'name_en' => 'Mauritania', 'code' => 'MRT', 'flag' => '🇲🇷', 'sort_order' => 135],
            ['name' => 'موریس', 'name_en' => 'Mauritius', 'code' => 'MUS', 'flag' => '🇲🇺', 'sort_order' => 136],
            ['name' => 'مایوت', 'name_en' => 'Mayotte', 'code' => 'YT', 'flag' => '', 'sort_order' => 137],
            ['name' => 'مکزیک', 'name_en' => 'Mexico', 'code' => 'MEX', 'flag' => '🇲🇽', 'sort_order' => 138],
            ['name' => 'میکرونزی', 'name_en' => 'Micronesia, Federated States of', 'code' => 'FSM', 'flag' => '🇫🇲', 'sort_order' => 139],
            ['name' => 'مولداوی', 'name_en' => 'Moldova, Republic of', 'code' => 'MDA', 'flag' => '🇲🇩', 'sort_order' => 140],
            ['name' => 'موناکو', 'name_en' => 'Monaco', 'code' => 'MCO', 'flag' => '🇲🇨', 'sort_order' => 141],
            ['name' => 'مغولستان', 'name_en' => 'Mongolia', 'code' => 'MNG', 'flag' => '🇲🇳', 'sort_order' => 142],
            ['name' => 'مونتسرات', 'name_en' => 'Montserrat', 'code' => 'MSR', 'flag' => '🇲🇸', 'sort_order' => 143],
            ['name' => 'مراکش', 'name_en' => 'Morocco', 'code' => 'MAR', 'flag' => '🇲🇦', 'sort_order' => 144],
            ['name' => 'موزامبیک', 'name_en' => 'Mozambique', 'code' => 'MOZ', 'flag' => '🇲🇿', 'sort_order' => 145],
            ['name' => 'میانمار', 'name_en' => 'Myanmar', 'code' => 'MMR', 'flag' => '🇲🇲', 'sort_order' => 146],
            ['name' => 'نامیبیا', 'name_en' => 'Namibia', 'code' => 'NAM', 'flag' => '🇳🇦', 'sort_order' => 147],
            ['name' => 'نائورو', 'name_en' => 'Nauru', 'code' => 'NRU', 'flag' => '🇳🇷', 'sort_order' => 148],
            ['name' => 'نپال', 'name_en' => 'Nepal', 'code' => 'NPL', 'flag' => '🇳🇵', 'sort_order' => 149],
            ['name' => 'هلند', 'name_en' => 'Netherlands', 'code' => 'NLD', 'flag' => '🇳🇱', 'sort_order' => 150],
            ['name' => 'آنتیل هلند', 'name_en' => 'Netherlands Antilles', 'code' => 'ANT', 'flag' => '', 'sort_order' => 151],
            ['name' => 'کالدونیای جدید', 'name_en' => 'New Caledonia', 'code' => 'NCL', 'flag' => '🇳🇨', 'sort_order' => 152],
            ['name' => 'نیوزیلند', 'name_en' => 'New Zealand', 'code' => 'NZL', 'flag' => '🇳🇿', 'sort_order' => 153],
            ['name' => 'نیکاراگوئه', 'name_en' => 'Nicaragua', 'code' => 'NIC', 'flag' => '🇳🇮', 'sort_order' => 154],
            ['name' => 'نیجر', 'name_en' => 'Niger', 'code' => 'NER', 'flag' => '🇳🇪', 'sort_order' => 155],
            ['name' => 'نیجریه', 'name_en' => 'Nigeria', 'code' => 'NGA', 'flag' => '🇳🇬', 'sort_order' => 156],
            ['name' => 'نیوئه', 'name_en' => 'Niue', 'code' => 'NIU', 'flag' => '🇳🇺', 'sort_order' => 157],
            ['name' => 'جزیره نورفولک', 'name_en' => 'Norfolk Island', 'code' => 'NFK', 'flag' => '🇳🇫', 'sort_order' => 158],
            ['name' => 'جزایر ماریانای شمالی', 'name_en' => 'Northern Mariana Islands', 'code' => 'MNP', 'flag' => '🇲🇵', 'sort_order' => 159],
            ['name' => 'نروژ', 'name_en' => 'Norway', 'code' => 'NOR', 'flag' => '🇳🇴', 'sort_order' => 160],
            ['name' => 'عمان', 'name_en' => 'Oman', 'code' => 'OMN', 'flag' => '🇴🇲', 'sort_order' => 161],
            ['name' => 'پاکستان', 'name_en' => 'Pakistan', 'code' => 'PAK', 'flag' => '🇵🇰', 'sort_order' => 162],
            ['name' => 'پالائو', 'name_en' => 'Palau', 'code' => 'PLW', 'flag' => '🇵🇼', 'sort_order' => 163],
            ['name' => 'سرزمین فلسطین', 'name_en' => 'Palestinian Territory, Occupied', 'code' => 'PS', 'flag' => '', 'sort_order' => 164],
            ['name' => 'پاناما', 'name_en' => 'Panama', 'code' => 'PAN', 'flag' => '🇵🇦', 'sort_order' => 165],
            ['name' => 'پاپوآ گینه نو', 'name_en' => 'Papua New Guinea', 'code' => 'PNG', 'flag' => '🇵🇬', 'sort_order' => 166],
            ['name' => 'پاراگوئه', 'name_en' => 'Paraguay', 'code' => 'PRY', 'flag' => '🇵🇾', 'sort_order' => 167],
            ['name' => 'پرو', 'name_en' => 'Peru', 'code' => 'PER', 'flag' => '🇵🇪', 'sort_order' => 168],
            ['name' => 'فیلیپین', 'name_en' => 'Philippines', 'code' => 'PHL', 'flag' => '🇵🇭', 'sort_order' => 169],
            ['name' => 'پیت‌کرن', 'name_en' => 'Pitcairn', 'code' => 'PCN', 'flag' => '🇵🇳', 'sort_order' => 170],
            ['name' => 'لهستان', 'name_en' => 'Poland', 'code' => 'POL', 'flag' => '🇵🇱', 'sort_order' => 171],
            ['name' => 'پرتغال', 'name_en' => 'Portugal', 'code' => 'PRT', 'flag' => '🇵🇹', 'sort_order' => 172],
            ['name' => 'پورتوریکو', 'name_en' => 'Puerto Rico', 'code' => 'PRI', 'flag' => '🇵🇷', 'sort_order' => 173],
            ['name' => 'قطر', 'name_en' => 'Qatar', 'code' => 'QAT', 'flag' => '🇶🇦', 'sort_order' => 174],
            ['name' => 'رئونیون', 'name_en' => 'Reunion', 'code' => 'REU', 'flag' => '🇷🇪', 'sort_order' => 175],
            ['name' => 'رومانی', 'name_en' => 'Romania', 'code' => 'ROM', 'flag' => '🇷🇴', 'sort_order' => 176],
            ['name' => 'روسیه', 'name_en' => 'Russian Federation', 'code' => 'RUS', 'flag' => '🇷🇺', 'sort_order' => 177],
            ['name' => 'روآندا', 'name_en' => 'Rwanda', 'code' => 'RWA', 'flag' => '🇷🇼', 'sort_order' => 178],
            ['name' => 'سنت هلنا', 'name_en' => 'Saint Helena', 'code' => 'SHN', 'flag' => '🇸🇭', 'sort_order' => 179],
            ['name' => 'سنت کیتس و نویس', 'name_en' => 'Saint Kitts and Nevis', 'code' => 'KNA', 'flag' => '🇰🇳', 'sort_order' => 180],
            ['name' => 'سنت لوسیا', 'name_en' => 'Saint Lucia', 'code' => 'LCA', 'flag' => '🇱🇨', 'sort_order' => 181],
            ['name' => 'سن پیر و میکلون', 'name_en' => 'Saint Pierre and Miquelon', 'code' => 'SPM', 'flag' => '🇵🇲', 'sort_order' => 182],
            ['name' => 'سنت وینسنت و گرنادین‌ها', 'name_en' => 'Saint Vincent and the Grenadines', 'code' => 'VCT', 'flag' => '🇻🇨', 'sort_order' => 183],
            ['name' => 'ساموآ', 'name_en' => 'Samoa', 'code' => 'WSM', 'flag' => '🇼🇸', 'sort_order' => 184],
            ['name' => 'سان مارینو', 'name_en' => 'San Marino', 'code' => 'SMR', 'flag' => '🇸🇲', 'sort_order' => 185],
            ['name' => 'سائوتومه و پرینسیپ', 'name_en' => 'Sao Tome and Principe', 'code' => 'STP', 'flag' => '🇸🇹', 'sort_order' => 186],
            ['name' => 'عربستان سعودی', 'name_en' => 'Saudi Arabia', 'code' => 'SAU', 'flag' => '🇸🇦', 'sort_order' => 187],
            ['name' => 'سنگال', 'name_en' => 'Senegal', 'code' => 'SEN', 'flag' => '🇸🇳', 'sort_order' => 188],
            ['name' => 'صربستان و مونته‌نگرو', 'name_en' => 'Serbia and Montenegro', 'code' => 'CS', 'flag' => '', 'sort_order' => 189],
            ['name' => 'سیشل', 'name_en' => 'Seychelles', 'code' => 'SYC', 'flag' => '🇸🇨', 'sort_order' => 190],
            ['name' => 'سیرالئون', 'name_en' => 'Sierra Leone', 'code' => 'SLE', 'flag' => '🇸🇱', 'sort_order' => 191],
            ['name' => 'سنگاپور', 'name_en' => 'Singapore', 'code' => 'SGP', 'flag' => '🇸🇬', 'sort_order' => 192],
            ['name' => 'اسلواکی', 'name_en' => 'Slovakia', 'code' => 'SVK', 'flag' => '🇸🇰', 'sort_order' => 193],
            ['name' => 'اسلوونی', 'name_en' => 'Slovenia', 'code' => 'SVN', 'flag' => '🇸🇮', 'sort_order' => 194],
            ['name' => 'جزایر سلیمان', 'name_en' => 'Solomon Islands', 'code' => 'SLB', 'flag' => '🇸🇧', 'sort_order' => 195],
            ['name' => 'سومالی', 'name_en' => 'Somalia', 'code' => 'SOM', 'flag' => '🇸🇴', 'sort_order' => 196],
            ['name' => 'آفریقای جنوبی', 'name_en' => 'South Africa', 'code' => 'ZAF', 'flag' => '🇿🇦', 'sort_order' => 197],
            ['name' => 'جورجیای جنوبی و جزایر ساندویچ جنوبی', 'name_en' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'flag' => '', 'sort_order' => 198],
            ['name' => 'اسپانیا', 'name_en' => 'Spain', 'code' => 'ESP', 'flag' => '🇪🇸', 'sort_order' => 199],
            ['name' => 'سریلانکا', 'name_en' => 'Sri Lanka', 'code' => 'LKA', 'flag' => '🇱🇰', 'sort_order' => 200],
            ['name' => 'سودان', 'name_en' => 'Sudan', 'code' => 'SDN', 'flag' => '🇸🇩', 'sort_order' => 201],
            ['name' => 'سورینام', 'name_en' => 'Suriname', 'code' => 'SUR', 'flag' => '🇸🇷', 'sort_order' => 202],
            ['name' => 'سوالبارد و یان ماین', 'name_en' => 'Svalbard and Jan Mayen', 'code' => 'SJM', 'flag' => '🇸🇯', 'sort_order' => 203],
            ['name' => 'اسواتینی', 'name_en' => 'Swaziland', 'code' => 'SWZ', 'flag' => '🇸🇿', 'sort_order' => 204],
            ['name' => 'سوئد', 'name_en' => 'Sweden', 'code' => 'SWE', 'flag' => '🇸🇪', 'sort_order' => 205],
            ['name' => 'سوئیس', 'name_en' => 'Switzerland', 'code' => 'CHE', 'flag' => '🇨🇭', 'sort_order' => 206],
            ['name' => 'سوریه', 'name_en' => 'Syrian Arab Republic', 'code' => 'SYR', 'flag' => '🇸🇾', 'sort_order' => 207],
            ['name' => 'تایوان', 'name_en' => 'Taiwan, Province of China', 'code' => 'TWN', 'flag' => '🇹🇼', 'sort_order' => 208],
            ['name' => 'تاجیکستان', 'name_en' => 'Tajikistan', 'code' => 'TJK', 'flag' => '🇹🇯', 'sort_order' => 209],
            ['name' => 'تانزانیا', 'name_en' => 'Tanzania, United Republic of', 'code' => 'TZA', 'flag' => '🇹🇿', 'sort_order' => 210],
            ['name' => 'تایلند', 'name_en' => 'Thailand', 'code' => 'THA', 'flag' => '🇹🇭', 'sort_order' => 211],
            ['name' => 'تیمور شرقی', 'name_en' => 'Timor-Leste', 'code' => 'TL', 'flag' => '', 'sort_order' => 212],
            ['name' => 'توگو', 'name_en' => 'Togo', 'code' => 'TGO', 'flag' => '🇹🇬', 'sort_order' => 213],
            ['name' => 'توکلائو', 'name_en' => 'Tokelau', 'code' => 'TKL', 'flag' => '🇹🇰', 'sort_order' => 214],
            ['name' => 'تونگا', 'name_en' => 'Tonga', 'code' => 'TON', 'flag' => '🇹🇴', 'sort_order' => 215],
            ['name' => 'ترینیداد و توباگو', 'name_en' => 'Trinidad and Tobago', 'code' => 'TTO', 'flag' => '🇹🇹', 'sort_order' => 216],
            ['name' => 'تونس', 'name_en' => 'Tunisia', 'code' => 'TUN', 'flag' => '🇹🇳', 'sort_order' => 217],
            ['name' => 'ترکیه', 'name_en' => 'Turkey', 'code' => 'TUR', 'flag' => '🇹🇷', 'sort_order' => 218],
            ['name' => 'ترکمنستان', 'name_en' => 'Turkmenistan', 'code' => 'TKM', 'flag' => '🇹🇲', 'sort_order' => 219],
            ['name' => 'جزایر تورکس و کایکوس', 'name_en' => 'Turks and Caicos Islands', 'code' => 'TCA', 'flag' => '🇹🇨', 'sort_order' => 220],
            ['name' => 'تووالو', 'name_en' => 'Tuvalu', 'code' => 'TUV', 'flag' => '🇹🇻', 'sort_order' => 221],
            ['name' => 'اوگاندا', 'name_en' => 'Uganda', 'code' => 'UGA', 'flag' => '🇺🇬', 'sort_order' => 222],
            ['name' => 'اوکراین', 'name_en' => 'Ukraine', 'code' => 'UKR', 'flag' => '🇺🇦', 'sort_order' => 223],
            ['name' => 'امارات متحده عربی', 'name_en' => 'United Arab Emirates', 'code' => 'ARE', 'flag' => '🇦🇪', 'sort_order' => 224],
            ['name' => 'بریتانیا', 'name_en' => 'United Kingdom', 'code' => 'GBR', 'flag' => '🇬🇧', 'sort_order' => 225],
            ['name' => 'ایالات متحده آمریکا', 'name_en' => 'United States', 'code' => 'USA', 'flag' => '🇺🇸', 'sort_order' => 226],
            ['name' => 'جزایر کوچک حاشیه‌ای ایالات متحده', 'name_en' => 'United States Minor Outlying Islands', 'code' => 'UM', 'flag' => '', 'sort_order' => 227],
            ['name' => 'اروگوئه', 'name_en' => 'Uruguay', 'code' => 'URY', 'flag' => '🇺🇾', 'sort_order' => 228],
            ['name' => 'ازبکستان', 'name_en' => 'Uzbekistan', 'code' => 'UZB', 'flag' => '🇺🇿', 'sort_order' => 229],
            ['name' => 'وانواتو', 'name_en' => 'Vanuatu', 'code' => 'VUT', 'flag' => '🇻🇺', 'sort_order' => 230],
            ['name' => 'ونزوئلا', 'name_en' => 'Venezuela', 'code' => 'VEN', 'flag' => '🇻🇪', 'sort_order' => 231],
            ['name' => 'ویتنام', 'name_en' => 'Viet Nam', 'code' => 'VNM', 'flag' => '🇻🇳', 'sort_order' => 232],
            ['name' => 'جزایر ویرجین بریتانیا', 'name_en' => 'Virgin Islands, British', 'code' => 'VGB', 'flag' => '🇻🇬', 'sort_order' => 233],
            ['name' => 'جزایر ویرجین آمریکا', 'name_en' => 'Virgin Islands, U.s.', 'code' => 'VIR', 'flag' => '🇻🇮', 'sort_order' => 234],
            ['name' => 'والیس و فوتونا', 'name_en' => 'Wallis and Futuna', 'code' => 'WLF', 'flag' => '🇼🇫', 'sort_order' => 235],
            ['name' => 'صحرای غربی', 'name_en' => 'Western Sahara', 'code' => 'ESH', 'flag' => '🇪🇭', 'sort_order' => 236],
            ['name' => 'یمن', 'name_en' => 'Yemen', 'code' => 'YEM', 'flag' => '🇾🇪', 'sort_order' => 237],
            ['name' => 'زامبیا', 'name_en' => 'Zambia', 'code' => 'ZMB', 'flag' => '🇿🇲', 'sort_order' => 238],
            ['name' => 'زیمبابوه', 'name_en' => 'Zimbabwe', 'code' => 'ZWE', 'flag' => '🇿🇼', 'sort_order' => 239],
        ];

        foreach ($countries as $countryData) {
            Country::create($countryData);
        }
    }
}
